### ISSUE TITLE
Drop support for `let` as `declaration_keyword`

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#163]
I can't think of a scenario where someone would want to actually use `let` as `declaration_keyword`. Although supporting it is very easy for us in code, I think that having the option available creates unnecessary confusion for people getting this set up.

**Comment by trotzig** [comment]
Yeah, I'm not sure either. Keeping it around is low-cost in terms of tech debt, but I can't see any problems with it being removed. If someone desperately needs it, reverting a removal commit is easy enough.

I added the `help wanted` label since I think this would be a good first issue to fix for a newcomer.
