### ISSUE TITLE
Add ability to run force fix imports on multiple files from the command line

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#173]
If you are working in a codebase that decides to switch from `const` to `import` syntax, it would be nice if there was a built-in way to run a command that would do all of this work for you.

**Comment by lencioni** [comment]
And maybe this shouldn't add or remove imports, but just update the current imports to match the style specified in the config. This should include things like declaration keyword, custom require function, excluding extensions, combining named exports, grouping (once that's a feature).

**Comment by trotzig** [comment]
A tricky thing here is that in order to resolve the configuration for an import, we sort of need it's full file path. The import statement itself isn't enough in some cases:

```js
const Foo = require('foo');
```

If we have local configuration for `app/**`, how do we know if `Foo` belongs to that local configuration or not? I guess we can do what `goto` does - try to resolve the import and out of the resolved `JSModule`s for `Foo`, check which ones end up in `'foo'` as the import path. Then use the file path from the `JSModule` to check config.

**Comment by trotzig** [comment]
As for batch-updating, I think we should just allow people to do something like this:

```bash
find . -name "*.js*" -exec import-js --filename {} --overwrite \;
```

Then we can just focus on making the command-line tool work well for one file.

**Comment by lencioni** [comment]
Yeah, that's fine. We can always add a command that makes that easier later if we need it.

**Comment by trotzig** [comment]
I've been thinking about this a little bit, and I think this is what we should do to begin with:

Introduce a new command alongside `fix_imports`, called `rewrite_imports`. We parse the file for current imports, then try to resolve each variable from those imports again, one by one. We'll use the same technique that `goto` uses in order to map ambiguous imports against the existing import statements. 

This technique should be pretty robust. The downside is that it will probably be slow, at least if we don't do any optimization.

**Comment by lencioni** [comment]
Slow is better than non-existent. That sounds like a fine starting point to me.
