### ISSUE TITLE
Add command to remove unused modules

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#21]
When working on a module I sometimes end up removing all references to a module that I had previously depended on. It would be nice if import-js could automatically remove the require statements for these for me similar to how it can add all missing modules by running `:ImportJSImportAll`.

I think importing and removing could be implemented as separate commands, and a third command could be added to do both at the same time--like an auto cleanup imports command. Or, if you don't see the value in keeping them separate, just roll it all into one command.

With this feature, it might work really well to automatically run this when saving .js files with something like:

```vim
autocmd BufWritePre *.js :ImportJSAutoFix
```

Then I could simply stop thinking about managing this bit of code in every file, freeing up my mind to think about more important things.

**Comment by trotzig** [comment]
Great suggestion! Since I started this project, my goal has been to implement this behavior. And we're almost there after the addition of `:ImportJSImportAll`. 

I suggest baking the removal of imports into that function as well. I don't see the value of having them separated to be honest. Back in the days, when I was using Eclipse and coding Java, I used the "Organize Imports" (Ctrl+Shift+O) function all the time. I suggest we rename the function at the same time to `:ImportJSOrganizeImports`.
