### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#22]
Sometimes when I run import-js, it takes a while for it to figure out what to import. I would like to set it up to run whenever I save a .js file so I can stop managing my require statements entirely, but before I do that it would be great if we could make this run faster.

One thing that might help would be to use some caching in the `find_files` method. It might work well to swap out the `Dir` calls for command line tools if they are available. Taking it a step further, it might be interesting to be able to optionally tap into other plugins' file listings, such as Command-T's file listing.

**Comment by trotzig** [comment]
Are you mostly talking about `:ImportJSImportAll`? I've noticed that being a bit slow (I get about 1.5 seconds on a relatively big component). I haven't really felt the pain when importing one variable. The import-all feature is a bit experimental at this point and there's improvement to be made.

Did you run any kind of profiling before making the conclusion that `find_files` is slow? I know it's highly likely that's the bottleneck but I just want to make sure we start in the right end so that we don't optimize something that doesn't matter.

I did a quick benchmark on `Dir.glob` and it looks like every lookup takes 0.16 seconds. I did this in the Brigade repository, with roughly 30,000 files.

```ruby
» time = Benchmark.measure do
↳   10.times { Dir.glob('**/**/button.js*') }
↳ end
» puts time
  0.310000   1.280000   1.590000 (  1.602583)
```

**Comment by lencioni** [comment]
> Are you mostly talking about `:ImportJSImportAll`?

No, I have actually not tried out that feature yet.

>  I haven't really felt the pain when importing one variable.

Most of the time it is fast, some times it is very slow. I'll try to dig in next time I notice slowness.

> Did you run any kind of profiling before making the conclusion that `find_files` is slow?

No, just assumptions. Actual profiling would be good before making modifications.

**Comment by trotzig** [comment]
I may have just made this worse with https://github.com/trotzig/import-js/commit/8324f8c9fc20de2c72311c4e3e53deff37be787e. Let me know how bad you think it is and I can come up with something smarter.

**Comment by lencioni** [comment]
I just tried it out and it seems to be noticeably slower than it was before, but I think it is still within the acceptable range for the project I was using it on. Not urgent, but if you can see an easy way to improve performance, it might be worth doing.

**Comment by trotzig** [comment]
Related: https://github.com/trotzig/import-js/compare/import-cache

This should improve performance slightly, at least for the second, third and consecutive imports.

**Comment by trotzig** [comment]
With https://github.com/trotzig/import-js/commit/2b7932e82d5363e84ba3e65f7a12d56b5bf86ba4, I'm going to close this issue. That commit brought down lookup times to <0.2s on my laptop on a fairly large codebase (Brigade). Feel free to reopen if you don't think it's good enough!
