### ISSUE TITLE
Auto import first match?

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#23]
I think that most times there are multiple matches, I want the first match. If import-js picked the first match in the priority order as defined in the configuration file, using the plugin would be a lot smoother. It could also stop searching after finding the first match which would make it faster in most cases.

**Comment by trotzig** [comment]
Interesting. Picking the first file was actually the default behavior, it changed to a selection list in this commit:
https://github.com/trotzig/import-js/commit/79f7a6e2ac2d5cbe74b9fc77793e8046bb47304b

That commit was written for good reasons. I found one example in the Brigade codebase where the "wrong" file was imported, and where it didn't help to reorder the lookup_paths config array. That's why I decided to do the selection list. 

I'm open to this kind of change, but I think it would be good to be able to turn it on/off through configuration (`aggressive_import: true|false` perhaps?). If you want to take a stab at implementing, go ahead. Otherwise I'll try to get to it when I have some time over.

**Comment by trotzig** [comment]
@lencioni: Do you still think this is something we would want? If so, feel free to re-open this issue.

**Comment by lencioni** [comment]
I'm not sure. It seems that with the recent improvements (`excludes` namely), this might not be nearly as useful. Also, I've noticed that the order of suggestions has changed recently, so I don't always want the first one anymore, so that would have to be adjusted before making this useful.

One alternative would be to remember the last thing you chose for that import and use that by default. If you want something different this time, run it again (or maybe another command) to get the whole list.
