### ISSUE TITLE
import_all does not recognise unused JSX classes

### ISSUE THREAD

**Issue by janpaul123** [trotzig/import-js#85]
I run into this frequently now, since I use Sublime Text which only supports import_all. It would never recognise `<Button>` as an unused variable.

**Comment by trotzig** [comment]
if you run `eslint` outside of import-js, does it then pick up the undefined jsx variables? This has been a problem on and off since I added import-all. The eslint call depends on the .eslintrc.js to be in good shape. I think it might have to do with having eslint 2 installed and our config using eslint 1 specific config:

```js
  'ecmaFeatures': {
    'jsx': true
  },
```
in eslint 2, this is 

```js
{
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  }
}
```

But I'm not actually sure. It doesn't work for me either, and I have eslint 1.10.1 installed.

**Comment by janpaul123** [comment]
Yep, it does catch it when just running `eslint` outside of import-js. -_-

**Comment by lencioni** [comment]
Is it possible that you have two different `eslint`s installed and that a different one is run in import-js vs outside of import-js?

**Comment by trotzig** [comment]
It turns out that we broke this a while ago in de3c9eeb.

Look at what eslint outputs for the `Ripple` not being defined:
```
   68:22  error  "contextualEventHelper" is not defined  no-undef
  159:8   error  'Ripple' is not defined                 react/jsx-no-undef
  217:11  error  "contextualEventHelper" is not defined  no-undef
```
The jsx plugin puts the variable in single quotes. I'll fix this and publish a new version soon.

**Comment by lencioni** [comment]
Ah! My bad. I'll look into submitting a PR to the React plugin to make this consistent with ESLint.

**Comment by trotzig** [comment]
Ah, that would be great!

**Comment by lencioni** [comment]
Actually, it seems that most ESLint rules use single quotes. So perhaps I'll submit a PR over there instead.
